### PR TITLE
Add Actor Interrupt Movement event

### PR DESCRIPTION
**Pull request by um3k**
Causes an actor to cancel its current movement event and stop at the next tile coordinate.

Inspired by this issue: https://github.com/chrismaltby/gb-studio/issues/1019
GB Studio counterpart: https://github.com/chrismaltby/gb-studio/pull/1036

### CODE REVIEW

**Comment by untoxa** [comment]
That feature need more complex solution, because you may have several concurrent scripts, which are moving several different actors. Actor movement code will be refactored.

**Comment by um3k** [comment]
I'm not sure I understand, this seems to work fine with multiple actors moving with their own update scripts. Of course, I would not be surprised to learn there are complexities I do not understand. 

https://user-images.githubusercontent.com/371786/151747065-361d7e93-8509-49ed-a61a-e5c62188b69b.mp4

**Comment by untoxa** [comment]
sorry, i looked through at night and did not notice that movement_interrupt is a property of actor, which is correct. grid snapping code looks a bit obscure. it also fires every loop, because actor->movement_interrupt is not reset after setting new destination.

**Comment by untoxa** [comment]
also please make the commit with the example project

**Comment by um3k** [comment]
All fair points, I will address them ASAP.

**Comment by um3k** [comment]
I'm not sure how I would make the grid snapping function less obscure. I added some comments and a const define to try to explain what it's doing a little better.

**Comment by untoxa** [comment]
ok. only please fix some style (brackets):
`if ((actor->pos.x < params->X) && (actor->pos.x & LOWEST_7_BITS)) {`
and probably 
`params->X = (actor->pos.x & ~LOWEST_7_BITS) | 128;`
will generate better code, need profiling.

LOWEST_7_BITS is not a good name either: why 7 bits, say, not 5? probably something like TILE_FRACTION_MASK will be better. also define ONE_TILE_DISTANCE 128

**Comment by um3k** [comment]
Thank you, those are excellent suggestions. I always struggle with naming
things, yet they seem so obvious now that you say them. I'll go ahead get
those all implemented.

**Pull request merged**
