### PR TITLE
Fix order of "On Enter"/"On Leave" execution

### PR DESCRIPTION
**Pull request by patrickmollohan**
Fixes issue [#1219 of GB Studio](https://github.com/chrismaltby/gb-studio/issues/1219).

### CODE REVIEW

**Comment by untoxa** [comment]
Note, that it should not make much difference, because scripts are executed in the parallel contexts.

**Comment by pau-tomas** [comment]
I didn't have time to do more testing (busy with work and life stuff :/ ) but the original report (https://github.com/chrismaltby/gb-studio/issues/1219) that this was working fine on 3.0.3. However trigger.c hasn't changed between that version and 3.1 other than cosmetic changes. Given what toxa said, the issue should be somewhere else then, right?

**Comment by untoxa** [comment]
yes, this might help in most of the cases, but there is no guarantee, that is what i am saying. you should write your code somehow not taking into account the fixed order of the enter/leave events.

**Comment by pau-tomas** [comment]
Was this always the case or has there been a specific change that modified the order behaviour?

**Comment by untoxa** [comment]
script_execute() spawns a concurrent thread, thus always.

**Comment by untoxa** [comment]
in 3.0 there was a problem with scripts, that sometimes (very often) threads were not spawned at all (spawned, but terminated immediately: https://github.com/chrismaltby/gbvm/commit/d81252195eb56fee4f85ad41ac5253d42e13aca6).

**Comment by nielsderijk** [comment]
Still [seems to be an issue for people](https://discord.com/channels/554713715442712616/585023243732123676/1123770444101734501): OnEnter is not triggered properly with adjecent triggers. I am also having issues in my game where 8x8 coins are floating next to each other.

**Comment by pau-tomas** [comment]
@nielsderijk I replied to #1345 which I think is the issue for the message you mention.

@untoxa could it be that, because trigger scripts are locked the fact that they run concurrently doesn't matter and they'll consistently execute on a given order. This is that when going from Trigger A to Trigger B: first `Trigger B.On Enter` and then `Trigger A.On Leave`?

It that's the case I think merging this PR will still make sense because A.On Leave > B.On Enter makes more sense than B.On Enter > A.On Leave.

**Comment by patrickmollohan** [comment]
Closing as it is out of date. May consider resubmitting in the future.

**Pull request closed without merging**
