### PR TITLE
Add atan2 function

### PR DESCRIPTION
**Pull request by patrickmollohan**
Useful for launching a projectile at an actor

### CODE REVIEW

**Comment by untoxa** [comment]
this is nice, but we are running out of bank2 (GBVM instructions) space. i'm going to refactor vm.c somehow first to solve that problem radically before merging.

**Comment by patrickmollohan** [comment]
Thanks! Yeah I noticed that while trying to add a vm_camera_get_draw_scroll function, which is why I ended up changing vm_camera_get_pos into a generic get function for both pos and draw_scroll. Perhaps something similar for the rest of the get/set functions could help?

**Comment by untoxa** [comment]
i will make something more radical

**Comment by pau-tomas** [comment]
@untoxa can this be merged now that the bank changes are in?

**Comment by untoxa** [comment]
i will check. probably atan table is too large for the bank 0, probably need to make that function banked.

**Pull request merged**
